version: "3.8"

services:
  db:
    image: postgres
    container_name: db
    env_file:
      - ./env/postgres.env
    volumes:
      - data:/var/lib/postgresql/data

  server:
    build: .
    container_name: server
    # env_file:
    #   - ./env/server.env
    volumes:
      - ./:/app
      - ./node_modules
    ports:
      - "3000:3000"
    command: npm run start:dev
    depends_on:
      - db

volumes: 
  data: